# Generated by Django 3.2.4 on 2021-06-23 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercancia',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Producto')),
                ('nombreproducto', models.CharField(max_length=20, verbose_name='Nombre del Producto')),
                ('stockproducto', models.IntegerField(verbose_name='Stock del producto')),
                ('precioproducto', models.IntegerField(verbose_name='Precio del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('idRango', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Rango')),
                ('nombreRango', models.CharField(max_length=50, verbose_name='Nombre deL Rango')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Usuario')),
                ('nombreusuario', models.CharField(max_length=20, verbose_name='Nombre del usuario')),
                ('contraseñausuario', models.CharField(max_length=20, verbose_name='Contraseña del usuario')),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuego.rango')),
            ],
        ),
    ]
