# Generated by Django 3.2.4 on 2021-06-28 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre deL Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('idRango', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Rango')),
                ('nombreRango', models.CharField(max_length=50, verbose_name='Nombre deL Rango')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut (sin punto ni guión)')),
                ('Contra', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('Mail', models.CharField(max_length=100, verbose_name='Mail')),
                ('Telefono', models.IntegerField(verbose_name='Teléfono')),
                ('Direccion', models.CharField(max_length=300, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Mercancia',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Producto')),
                ('nombreproducto', models.CharField(max_length=20, verbose_name='Nombre del Producto')),
                ('stockproducto', models.IntegerField(verbose_name='Stock del producto')),
                ('precioproducto', models.IntegerField(verbose_name='Precio del producto')),
                ('imagen', models.ImageField(null=True, upload_to='Imagenes')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuego.categoria')),
            ],
        ),
    ]
