# Generated by Django 3.2.4 on 2021-06-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Rut',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut '),
        ),
    ]
